import React from 'react';
import { View, Text, ScrollView, StyleSheet, TouchableOpacity, useColorScheme } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { Colors } from '@/constants/Colors';

const SECTIONS = [
  {
    title: '1. Information We Collect',
    body: 'When you create an account, book a tour or hotel, or use Daily Mode, we collect information you provide directly (name, email, phone number, payment details) as well as information generated by using the app, such as your live location (only while Daily Mode or live tracking is active), trip history, and preferences used for AI trip recommendations.',
  },
  {
    title: '2. How We Use Your Information',
    body: 'We use your information to process bookings, generate route and itinerary recommendations, send booking confirmations and newsletter updates, calculate live fuel costs and nearby points of interest, and improve the reliability of our tours and daily-mode features.',
  },
  {
    title: '3. Location Data',
    body: 'Live GPS location is used only to power features you have actively opened, such as live map tracking, proximity alerts when nearing points of interest, and route recalculation. You can revoke location access at any time from your device settings, which will disable these features but not the rest of the app.',
  },
  {
    title: '4. Sharing of Information',
    body: 'We do not sell personal information. Booking details are shared with the relevant hotel, tour guide, or vehicle provider strictly to fulfil your reservation. We may use third-party services (mapping, weather, fuel price providers) that receive only the minimum data required, such as coordinates for a route query.',
  },
  {
    title: '5. Data Retention',
    body: 'Account and booking data is retained for as long as your account is active. You may request deletion of your account and associated data at any time from your profile settings.',
  },
  {
    title: '6. Your Rights',
    body: 'You may access, correct, or delete your personal data, and unsubscribe from the newsletter at any time using the link included in every email we send.',
  },
  {
    title: '7. Contact',
    body: 'Questions about this policy can be sent to hello@serendib.lk.',
  },
];

export default function PrivacyScreen() {
  const scheme = useColorScheme();
  const theme = scheme === 'dark' ? Colors.dark : Colors.light;
  const router = useRouter();

  return (
    <View style={[styles.root, { backgroundColor: theme.background }]}>
      <SafeAreaView edges={['top']} style={styles.headerSafe}>
        <View style={styles.header}>
          <TouchableOpacity style={styles.backBtn} onPress={() => router.back()}>
            <Text style={[styles.backBtnText, { color: theme.text }]}>‹</Text>
          </TouchableOpacity>
          <Text style={[styles.headerTitle, { color: theme.text }]}>Privacy Policy</Text>
          <View style={{ width: 38 }} />
        </View>
      </SafeAreaView>
      <ScrollView contentContainerStyle={{ padding: 16, paddingBottom: 40 }} showsVerticalScrollIndicator={false}>
        <Text style={[styles.updated, { color: theme.textSecondary }]}>Last updated: July 2026</Text>
        {SECTIONS.map((s) => (
          <View key={s.title} style={{ marginBottom: 20 }}>
            <Text style={[styles.sectionTitle, { color: theme.text }]}>{s.title}</Text>
            <Text style={[styles.sectionBody, { color: theme.textSecondary }]}>{s.body}</Text>
          </View>
        ))}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1 },
  headerSafe: { borderBottomWidth: 0 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 8, paddingVertical: 8 },
  backBtn: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center' },
  backBtnText: { fontSize: 26, marginTop: -2 },
  headerTitle: { fontSize: 17, fontWeight: '700' },
  updated: { fontSize: 12, marginBottom: 20 },
  sectionTitle: { fontSize: 16, fontWeight: '700', marginBottom: 6 },
  sectionBody: { fontSize: 14, lineHeight: 21 },
});
