import { motion } from "framer-motion";
import { ShieldCheck } from "lucide-react";

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-sand-50 pt-32 pb-24 px-5 md:px-8">
      <div className="max-w-3xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7 }}
        >
          <div className="flex items-center gap-2 text-[11px] tracking-[0.35em] uppercase text-leaf-700 font-semibold mb-3">
            <ShieldCheck className="w-4 h-4" /> Legal
          </div>
          <h1 className="font-serif text-4xl md:text-5xl text-ink-900 mb-3">Privacy Policy</h1>
          <p className="text-ink-800/60 text-sm mb-12">Last updated: July 2026</p>

          <div className="space-y-8 text-ink-800/80 leading-relaxed text-sm md:text-base">
            <section>
              <h2 className="font-serif text-xl text-ink-900 mb-2">1. Information We Collect</h2>
              <p>
                When you create an account, book a tour or hotel, or use Daily Mode, we collect
                information you provide directly (name, email, phone number, payment details) as
                well as information generated by using the app, such as your live location (only
                while Daily Mode or live tracking is active), trip history, and preferences used
                for AI trip recommendations.
              </p>
            </section>

            <section>
              <h2 className="font-serif text-xl text-ink-900 mb-2">2. How We Use Your Information</h2>
              <p>
                We use your information to process bookings, generate route and itinerary
                recommendations, send booking confirmations and newsletter updates (only if you
                subscribed), calculate live fuel costs and nearby points of interest, and improve
                the reliability of our tours and daily-mode features.
              </p>
            </section>

            <section>
              <h2 className="font-serif text-xl text-ink-900 mb-2">3. Location Data</h2>
              <p>
                Live GPS location is used only to power features you have actively opened, such as
                live map tracking, proximity alerts when nearing points of interest, and route
                recalculation. Location access can be revoked at any time from your device
                settings, which will disable these features but not the rest of the app.
              </p>
            </section>

            <section>
              <h2 className="font-serif text-xl text-ink-900 mb-2">4. Sharing of Information</h2>
              <p>
                We do not sell personal information. Booking details are shared with the relevant
                hotel, tour guide, or vehicle provider strictly to fulfil your reservation. We may
                use third-party services (such as mapping, weather, and fuel price providers) that
                receive only the minimum data required to return a result, such as coordinates for
                a route query.
              </p>
            </section>

            <section>
              <h2 className="font-serif text-xl text-ink-900 mb-2">5. Data Retention</h2>
              <p>
                Account and booking data is retained for as long as your account is active. You may
                request deletion of your account and associated data at any time from your profile
                settings or by contacting us directly.
              </p>
            </section>

            <section>
              <h2 className="font-serif text-xl text-ink-900 mb-2">6. Your Rights</h2>
              <p>
                You may access, correct, or delete your personal data, and unsubscribe from the
                newsletter at any time using the link included in every email we send.
              </p>
            </section>

            <section>
              <h2 className="font-serif text-xl text-ink-900 mb-2">7. Contact</h2>
              <p>
                Questions about this policy can be sent to{" "}
                <a href="mailto:hello@serendib.lk" className="text-leaf-700 underline">
                  hello@serendib.lk
                </a>.
              </p>
            </section>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
